# Название рабочего процесса
name: PyCI

# События, при которых будет запускаться рабочий процесс
on:
  - push # Запуск при каждом push в репозиторий

# Задачи, которые нужно выполнить
jobs:
  build: # Имя задачи
    runs-on: ubuntu-latest # Операционная система, на которой будет выполняться задача
    strategy:
      matrix:
        python-version: [3.11, 3.12] # Версии Python для тестирования

    steps: # Шаги для выполнения в задаче
      - uses: actions/checkout@v3 # Шаг для проверки репозитория

      # Шаг для установки Python с использованием версии из матрицы стратегии
      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      # Шаг для установки зависимостей через pip и make
      - name: install-dependencies
        run: pip install poetry && make install

      # Шаг для проверки кода линтером
      - name: check linter
        run: make lint

      # Шаг для проверки покрытия кода тестами и отправки отчета в CodeClimate
      - name: checking coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}} # Использование секрета для идентификатора отчета
        with:
          coverageCommand: make coverage # Команда для генерации отчета о покрытии
          debug: true # Включение режима отладки
